### ISSUE TITLE
Outdated Version?

### ISSUE THREAD

**Issue by 21stCheran** [ST-DDT/CrazyLogin#11]
07:58:56 INFO]: [CrazyLogin] Enabling CrazyLogin v7.24.0*
[07:58:56 ERROR]: Error occurred while enabling CrazyLogin v7.24.0 (Is it up to date?)
java.lang.IllegalArgumentException: Channel must contain : separator (attempted to use CrazyLogin)
	at org.bukkit.plugin.messaging.StandardMessenger.validateAndCorrectChannel(StandardMessenger.java:474) ~[Paper-latest.jar:git-Paper-353]
	at org.bukkit.plugin.messaging.StandardMessenger.registerIncomingPluginChannel(StandardMessenger.java:209) ~[Paper-latest.jar:git-Paper-353]
	at de.st_ddt.crazylogin.CrazyLogin.registerHooks(CrazyLogin.java:1466) ~[?:?]
	at de.st_ddt.crazylogin.CrazyLogin.onEnable(CrazyLogin.java:1612) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[Paper-latest.jar:git-Paper-353]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[Paper-latest.jar:git-Paper-353]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[Paper-latest.jar:git-Paper-353]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:438) ~[Paper-latest.jar:git-Paper-353]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:352) ~[Paper-latest.jar:git-Paper-353]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613) ~[Paper-latest.jar:git-Paper-353]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:575) ~[Paper-latest.jar:git-Paper-353]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435) ~[Paper-latest.jar:git-Paper-353]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:311) ~[Paper-latest.jar:git-Paper-353]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[Paper-latest.jar:git-Paper-353]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[07:58:56 INFO]: [CrazyLogin] Disabling CrazyLogin v7.24.0
[07:58:56 ERROR]: Error occurred while disabling CrazyLogin v7.24.0 (Is it up to date?)
java.lang.NullPointerException: null
	at de.st_ddt.crazylogin.CrazyLogin.saveConfiguration(CrazyLogin.java:1799) ~[?:?]
	at de.st_ddt.crazyplugin.CrazyPlayerDataPlugin.onDisable(CrazyPlayerDataPlugin.java:298) ~[?:?]
	at de.st_ddt.crazylogin.CrazyLogin.onDisable(CrazyLogin.java:1625) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[Paper-latest.jar:git-Paper-353]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:359) ~[Paper-latest.jar:git-Paper-353]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) ~[Paper-latest.jar:git-Paper-353]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[Paper-latest.jar:git-Paper-353]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:438) ~[Paper-latest.jar:git-Paper-353]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:352) ~[Paper-latest.jar:git-Paper-353]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613) ~[Paper-latest.jar:git-Paper-353]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:575) ~[Paper-latest.jar:git-Paper-353]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435) ~[Paper-latest.jar:git-Paper-353]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:311) ~[Paper-latest.jar:git-Paper-353]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[Paper-latest.jar:git-Paper-353]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
[07:58:56 INFO]: Done (5.553s)! For help, type "help"
[07:58:56 INFO]: Timings Reset
> plugins
[07:59:17 INFO]: Plugins (2): CrazyCore*, CrazyLogin*(CrazyLogin is shown in red)

This server is running Paper version git-Paper-353 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

**Comment by ST-DDT** [comment]
Thanks for your report.
I uploaded a build for MC 1.13.1 (https://dev.bukkit.org/projects/crazylogin/files/2628540)
Please report any issues you might encounter.
