### ISSUE TITLE
Not starting up - server version 1.13.2

### ISSUE THREAD

**Issue by 21stCheran** [ST-DDT/CrazyLogin#13]
````
[23:58:54] [Server thread/INFO]: [CrazyLogin] Loading CrazyLogin v7.24.0
[23:59:03] [Server thread/INFO]: [CrazyLogin] Enabling CrazyLogin v7.24.0*
[23:59:03] [Server thread/ERROR]: Error occurred while enabling CrazyLogin v7.24.0 (Is it up to date?)
java.lang.IllegalArgumentException: Channel must contain : separator (attempted to use CrazyLogin)
	at de.st_ddt.crazylogin.CrazyLogin.registerHooks(CrazyLogin.java:1466) ~[?:?]
	at de.st_ddt.crazylogin.CrazyLogin.onEnable(CrazyLogin.java:1612) ~[?:?]
[23:59:03] [Server thread/INFO]: [CrazyLogin] Disabling CrazyLogin v7.24.0
[23:59:03] [Server thread/ERROR]: Error occurred while disabling CrazyLogin v7.24.0 (Is it up to date?)
	at de.st_ddt.crazylogin.CrazyLogin.saveConfiguration(CrazyLogin.java:1799) ~[?:?]
	at de.st_ddt.crazylogin.CrazyLogin.onDisable(CrazyLogin.java:1625) 
````

**CRAZY CORE DATA**
````
[23:58:54] [Server thread/INFO]: [CrazyCore] Loading CrazyCore v10.7.10
[23:59:01] [Server thread/INFO]: [CrazyCore] Enabling CrazyCore v10.7.10*
[23:59:01] [Server thread/INFO]: [CrazyCore] Checking permission modules:
[23:59:01] [Server thread/INFO]: [CrazyCore] - Vault
[23:59:01] [Server thread/INFO]: [CrazyCore] Activated Vault Permission Module!
[23:59:01] [Server thread/INFO]: [CrazyCore] Loading languages...
[23:59:01] [Server thread/INFO]: [CrazyCore] gr_gr language files not available!
[23:59:01] [Server thread/INFO]: [CrazyCore] Version 10.7.10 enabled
````

**Comment by ST-DDT** [comment]
Have you tried running CrazyLogin 2.24.2?

**Comment by 21stCheran** [comment]
Apologies, I was able to get the correct version 7.24.2 in the updates section. However, when I chose 'Download Latest File' it gave me 7.24.0 hence I assumed it was the latest.

**Comment by ST-DDT** [comment]
No problem.
